name: Publish image

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Build and publish Docker image
        uses: elgohr/Publish-Docker-Github-Action@2.8
        with:
          name: owner/repository/image
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: docker.pkg.github.com
          tagnames: true
